In [1]:
import pandas as pd
Raw_Housing_Data=pd.read_csv("/content/drive/My Drive/MLInternshaala/Raw_Housing_Prices3.csv")

In [2]:
Raw_Housing_Data.describe()

                 ID  ...  Lot Area after Renovation (in Sqft)
count  2.160900e+04  ...                         21609.000000
mean   4.580686e+09  ...                         12769.770790
std    2.876653e+09  ...                         27306.508841
min    1.000102e+06  ...                           651.000000
25%    2.123049e+09  ...                          5100.000000
50%    3.904931e+09  ...                          7620.000000
75%    7.308900e+09  ...                         10084.000000
max    9.900000e+09  ...                        871200.000000

[8 rows x 17 columns]

In [3]:
Raw_Housing_Data['Zipcode'].isnull().sum()

0

In [4]:
Raw_Housing_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21609 entries, 0 to 21608
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21609 non-null  int64
 1   Date House was Sold                        21609 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21609 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21609 non-null  float64
 6   Lot Area (in Sqft)                         21609 non-null  float64
 7   No of Floors                               21609 non-null  float64
 8   Waterfront View                            21609 non-null  object
 9   No of Times Visited                        21609 non-null  object
 10  Condition of the House                     21609 non-null  object
 11  Overall Grade                              21609 non-null  int64
 12  Area of the House from Basement (in Sqft)  21609 non-null  float64
 13  Basement Area (in Sqft)                    21609 non-null  int64
 14  Age of House (in Years)                    21609 non-null  int64
 15  Renovated Year                             21609 non-null  int64
 16  Zipcode                                    21609 non-null  float64
 17  Latitude                                   21609 non-null  float64
 18  Longitude                                  21609 non-null  float64
 19  Living Area after Renovation (in Sqft)     21609 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21609 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [5]:
Raw_Housing_Data['Zipcode']=Raw_Housing_Data['Zipcode'].astype(object)
Raw_Housing_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21609 entries, 0 to 21608
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21609 non-null  int64
 1   Date House was Sold                        21609 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21609 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21609 non-null  float64
 6   Lot Area (in Sqft)                         21609 non-null  float64
 7   No of Floors                               21609 non-null  float64
 8   Waterfront View                            21609 non-null  object
 9   No of Times Visited                        21609 non-null  object
 10  Condition of the House                     21609 non-null  object
 11  Overall Grade                              21609 non-null  int64
 12  Area of the House from Basement (in Sqft)  21609 non-null  float64
 13  Basement Area (in Sqft)                    21609 non-null  int64
 14  Age of House (in Years)                    21609 non-null  int64
 15  Renovated Year                             21609 non-null  int64
 16  Zipcode                                    21609 non-null  object
 17  Latitude                                   21609 non-null  float64
 18  Longitude                                  21609 non-null  float64
 19  Living Area after Renovation (in Sqft)     21609 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21609 non-null  int64
dtypes: float64(9), int64(7), object(5)
memory usage: 3.5+ MB

In [7]:
Raw_Housing_Data['No of Times Visited'].unique()

array(['None', 'Thrice', 'Four', 'Twice', 'Once'], dtype=object)

In [8]:
mapping={'None':'0','Once':'1','Twice':'2','Thrice':'3','Four':'4'}

In [9]:
Raw_Housing_Data['No of Times Visited'] =Raw_Housing_Data['No of Times Visited'].map(mapping)

In [10]:
Raw_Housing_Data['No of Times Visited'].unique()

array(['0', '3', '4', '2', '1'], dtype=object)

In [12]:
import numpy as np
Raw_Housing_Data['Ever Renovated']=np.where(Raw_Housing_Data['Renovated Year']==0,'No','Yes')

In [13]:
Raw_Housing_Data['Ever Renovated']

0         No
1        Yes
2         No
3         No
4         No
        ...
21604     No
21605     No
21606     No
21607     No
21608     No
Name: Ever Renovated, Length: 21609, dtype: object

In [14]:
Raw_Housing_Data['Purchase_year']=pd.DatetimeIndex(Raw_Housing_Data['Date House was Sold']).year

In [15]:
Raw_Housing_Data['Years since Renovation'] =np.where(Raw_Housing_Data['Ever Renovated']=='Yes',abs(Raw_Housing_Data['Renovated Year'] - Raw_Housing_Data['Purchase_year']),0)

In [16]:
Raw_Housing_Data['Purchase_year']

0        2017
1        2017
2        2016
3        2017
4        2016
         ...
21604    2017
21605    2016
21606    2017
21607    2016
21608    2017
Name: Purchase_year, Length: 21609, dtype: int64

In [17]:
Raw_Housing_Data['Ever Renovated']

0         No
1        Yes
2         No
3         No
4         No
        ...
21604     No
21605     No
21606     No
21607     No
21608     No
Name: Ever Renovated, Length: 21609, dtype: object

In [18]:
Raw_Housing_Data['Years since Renovation']

0         0
1        26
2         0
3         0
4         0
         ..
21604     0
21605     0
21606     0
21607     0
21608     0
Name: Years since Renovation, Length: 21609, dtype: int64

In [19]:
Raw_Housing_Data.drop(columns=['Purchase_year','Date House was Sold','Renovated Year'],inplace=True)

In [20]:
Raw_Housing_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21609 entries, 0 to 21608
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21609 non-null  int64
 1   Sale Price                                 21609 non-null  float64
 2   No of Bedrooms                             21609 non-null  int64
 3   No of Bathrooms                            21609 non-null  float64
 4   Flat Area (in Sqft)                        21609 non-null  float64
 5   Lot Area (in Sqft)                         21609 non-null  float64
 6   No of Floors                               21609 non-null  float64
 7   Waterfront View                            21609 non-null  object
 8   No of Times Visited                        21609 non-null  object
 9   Condition of the House                     21609 non-null  object
 10  Overall Grade                              21609 non-null  int64
 11  Area of the House from Basement (in Sqft)  21609 non-null  float64
 12  Basement Area (in Sqft)                    21609 non-null  int64
 13  Age of House (in Years)                    21609 non-null  int64
 14  Zipcode                                    21609 non-null  object
 15  Latitude                                   21609 non-null  float64
 16  Longitude                                  21609 non-null  float64
 17  Living Area after Renovation (in Sqft)     21609 non-null  float64
 18  Lot Area after Renovation (in Sqft)        21609 non-null  int64
 19  Ever Renovated                             21609 non-null  object
 20  Years since Renovation                     21609 non-null  int64
dtypes: float64(9), int64(7), object(5)
memory usage: 3.5+ MB

In [21]:
Raw_Housing_Data['Sale Price'].corr(Raw_Housing_Data['Flat Area (in Sqft)'])

0.6951704258420669

Using Numpy Library

In [22]:
np.corrcoef(Raw_Housing_Data['Sale Price'],Raw_Housing_Data['Flat Area (in Sqft)'])

array([[1.        , 0.69517043],
       [0.69517043, 1.        ]])

Correlation of each variable with all other variables

In [23]:
Raw_Housing_Data.corr()

                                                 ID  ...  Years since Renovation
ID                                         1.000000  ...               -0.016227
Sale Price                                -0.011529  ...                0.065907
No of Bedrooms                             0.001450  ...               -0.007198
No of Bathrooms                            0.005233  ...                0.003551
Flat Area (in Sqft)                       -0.012379  ...                0.023503
Lot Area (in Sqft)                        -0.132153  ...                0.013835
No of Floors                               0.018653  ...               -0.000901
Overall Grade                              0.013762  ...               -0.024388
Area of the House from Basement (in Sqft) -0.010724  ...                0.010491
Basement Area (in Sqft)                   -0.005189  ...                0.029158
Age of House (in Years)                   -0.021524  ...                0.203375
Latitude                                  -0.001983  ...                0.019739
Longitude                                  0.020720  ...               -0.055039
Living Area after Renovation (in Sqft)    -0.002913  ...               -0.008390
Lot Area after Renovation (in Sqft)       -0.138843  ...                0.011289
Years since Renovation                    -0.016227  ...                1.000000

[16 rows x 16 columns]

In [25]:
Raw_Housing_Data.drop(columns=['ID']).corr()

                                           Sale Price  ...  Years since Renovation
Sale Price                                   1.000000  ...                0.065907
No of Bedrooms                               0.339407  ...               -0.007198
No of Bathrooms                              0.535124  ...                0.003551
Flat Area (in Sqft)                          0.695170  ...                0.023503
Lot Area (in Sqft)                           0.101319  ...                0.013835
No of Floors                                 0.298913  ...               -0.000901
Overall Grade                                0.680914  ...               -0.024388
Area of the House from Basement (in Sqft)    0.606527  ...                0.010491
Basement Area (in Sqft)                      0.307513  ...                0.029158
Age of House (in Years)                     -0.064306  ...                0.203375
Latitude                                     0.402430  ...                0.019739
Longitude                                    0.045401  ...               -0.055039
Living Area after Renovation (in Sqft)       0.629944  ...               -0.008390
Lot Area after Renovation (in Sqft)          0.092325  ...                0.011289
Years since Renovation                       0.065907  ...                1.000000

[15 rows x 15 columns]

In [26]:
Raw_Housing_Data

               ID  Sale Price  ...  Ever Renovated  Years since Renovation
0      7129300520    221900.0  ...              No                       0
1      6414100192    538000.0  ...             Yes                      26
2      5631500400    180000.0  ...              No                       0
3      2487200875    604000.0  ...              No                       0
4      1954400510    510000.0  ...              No                       0
...           ...         ...  ...             ...                     ...
21604   263000018    360000.0  ...              No                       0
21605  6600060120    400000.0  ...              No                       0
21606  1523300141    402101.0  ...              No                       0
21607   291310100    400000.0  ...              No                       0
21608  1523300157    325000.0  ...              No                       0

[21609 rows x 21 columns]